services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post
      POSTGRES_DB: roadmap
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - roadmap-app
    restart: on-failure
  
  roadmap.presentation:
    image: roadmap.presentation
    build:
      context: .
      dockerfile: Roadmap.Presentation/Dockerfile
    depends_on:
      - db
    networks:
      - roadmap-app
    restart: on-failure

networks:
  roadmap-app:

volumes:
  db-data:
